### ISSUE TITLE
`konduit init` does not copy an uber jar to ~/.konduit/konduit-serving/konduit.jar

### ISSUE THREAD

**Issue by kmotohas** [KonduitAI/konduit-serving#116]
In the document of python sdk, an uber jar of konduit-serving is supposed to be ~/.konduit/konduit-serving/konduit.jar. 
But `konduit init` does not make a copy of a uber jar there.

I think it is more user friendly to make a copy (or symbolic link) as `build_jar.py` does.

**Comment by maxpumperla** [comment]
@kmotohas I'm not sure I understand. `konduit init` _literally_ uses `build_jar.py` to build the uberjar into that exact path (i.e. `~/.konduit/konduit-serving/konduit.jar`). there is no need to copy it anywhere else after.
