### ISSUE TITLE
TensorFlow conf does not get (input) data formats from Server

### ISSUE THREAD

**Issue by philip-khor** [KonduitAI/konduit-serving#124]
As of commit 60a3539dbca656fdb6ba11328d8b72a5f773bb91 Client objects get information on names and formats from the server, instead of defaulting to NUMPY for input and output. 

However it seems like [this TensorFlow configuration](https://github.com/KonduitAI/konduit-serving-examples/blob/master/yaml/tensorflow-mnist.yaml) is not inheriting data formats from the Server. When I run `konduit predict-numpy` or `client.predict()` I get an error similar to the following:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-5f56ec126093> in <module>
      1 plt.imshow(img)
      2 predicted = client.predict(
----> 3     data_input={'input_layer': img}
      4 )
      5 plt.show()

~\AppData\Local\Continuum\miniconda3\envs\pytorch\lib\site-packages\konduit-0.1.4-py3.7.egg\konduit\client.py in predict(self, data_input)
    104         if data_input is None:
    105             data_input = {}
--> 106         if self.input_format.upper() == "JSON":
    107             resp = requests.post(
    108                 "{}/{}/{}".format(

AttributeError: 'NoneType' object has no attribute 'upper'
```

This is resolved when I add `input_data_format: NUMPY` to the YAML configuration. However I can run Deeplearning4j and Python configurations even when data formats are left out from the Client.

**Comment by ShamsUlAzeem** [comment]
The input and output data formats aren't taken from the server since we had to make sense of some of the use cases. It will be added shortly.

**Comment by ShamsUlAzeem** [comment]
the `get_client()` method needs to be updated too at some ends for this

**Comment by maxpumperla** [comment]
https://github.com/KonduitAI/konduit-serving/blob/master/python/konduit/server.py#L99-L103

https://github.com/KonduitAI/konduit-serving/blob/master/python/konduit/client.py#L65-L70

@ShamsUlAzeem @philip-khor we intend to do this here. I suspect that this check prevents us from getting the correct info:

https://github.com/KonduitAI/konduit-serving/blob/master/python/konduit/client.py#L48

I'll look into it.

**Comment by maxpumperla** [comment]
ah, I understand this better now. thanks for the other issue @ShamsUlAzeem. I'm fixing `client_from_file` to get stuff from the server as well. that's all we need.

**Comment by maxpumperla** [comment]
@philip-khor we have a unit test for your case now. the new logic is as follows:

if you provide a `client` section in your konduit.yaml, then it has to be complete and include all data. If you don't have such a section, it will read the `serving` properties and get info from the server (which assumes a running server,  but that's all).
