### ISSUE TITLE
There is no requirement to install konduit-serving

### ISSUE THREAD

**Issue by kkoj** [KonduitAI/konduit-serving#128]
This page does not has a description of requirements, versions of OS, python, JVM, etc.
https://serving.oss.konduit.ai/installation
It would be better for being a document.

**Comment by philip-khor** [comment]
Will update for clarity. Please see also #125

**Comment by philip-khor** [comment]
Preliminary system requirements have been written up at https://serving.oss.konduit.ai/installation#system-requirements. I'm aware of febc8453813875b6f14faf67c957f5614bdee9e5, but as of now we're still at CUDA 10.1. 

RAM and CPU requirements omitted as they depend on the model being served.

cc @ShamsUlAzeem
