### ISSUE TITLE
Document Konduit Monitoring capabilities

### ISSUE THREAD

**Issue by ShamsUlAzeem** [KonduitAI/konduit-serving#139]
We have a few basic examples of metrics with Konduit using prometheus and grafana in the `docker` folder. What we need to do is to salvage them and format them properly for documentation. 

### Examples
- [ ] List out the content related to metrics inside the `docker` folder. 
- [x] Create workflow examples (without docker) for utilizing prometheus and grafana that includes configuration details. 
- [x] Upload the source code into the [konduit-serving-examples](https://github.com/KonduitAI/konduit-serving-examples) repo.

### Documentation
- [x] Document the workflows into [docs repo](https://github.com/KonduitAI/konduit-serving-docs).
- [x] Sync new items with gitbook.

**Comment by philip-khor** [comment]
Worked on at https://github.com/KonduitAI/konduit-serving-examples/tree/philip/monitoring/monitoring/

**Comment by philip-khor** [comment]
## List out the content related to metrics inside the docker folder.

The content inside the docker folder relevant to this task are `server_with_metrics` and `server_with_metrics_computer_vision`. To me, these two are identical. Their Konduit Serving configuration `config.json` files don't alter the metrics defaults:

https://github.com/KonduitAI/konduit-serving/blob/b247b211d5e2441e781ddc960bfed12dff446890/konduit-serving-api/src/main/java/ai/konduit/serving/config/ServingConfig.java#L63-L71

and their Grafana configurations `dashboard.json` appear identical. In terms of documenting monitoring capabilities, these examples are redundant and imo do not need to be ported. 

We may want more documentation on which metrics to pick for which scenario. It may be useful to gather a few combinations of metrics and provide a few sample `dashboard.json` files for different monitoring use cases.

I have also included content from docker/notes/grafana.ipynb and docker/notes/prometheus.ipynb, and some new content based on my understanding of the metrics endpoint.
