### ISSUE TITLE
Install JAR under the hood for python users (like pydl4j does)

### ISSUE THREAD

**Issue by maxpumperla** [KonduitAI/konduit-serving#16]
Right now, users can't just install `konduit`, they have to clone this repo, build a jar, copy the jar and set a path variable.

we should have a mechanism like pydl4j in place that takes care of all of that without users knowing about it. that could in fact be in `pydl4j` itself, as this was built to be a jar manager in the first place.

**Comment by saudet** [comment]
BTW, since we're already using Java here, what's the downside with just using Maven?

**Comment by maxpumperla** [comment]
it will use maven either way (pydl4j does so under the hood). for instance, we use batteries-included `mvnw` here, which is already a good option. the point is to make it as simple as possible for "basic python users" to use our software. and telling them to first install `mvn` etc., they'll likely just move on.

**Comment by saudet** [comment]
I plan to do something like that for the JavaCPP-based distributions. It'll probably be using some Bash script like `mvnw` yeah...

**Comment by maxpumperla** [comment]
ideally, I'd like to expose a tiny cli tool like this:

```pip install konduit
konduit build
```

and this build step would, e.g., clone this repo, run `mvnw` with the proper options (maybe even inferring the platform used somehow?) and putting the resulting uberjar into, say, `~/.konduit/konduit.jar` so your python code will automatically look there.

**Comment by saudet** [comment]
Sounds like a `conda-pack`. Yeah, sure, I'd see that as part of my stuff as well.

**Comment by agibsonccc** [comment]
@saudet @maxpumperla  Kinda curious if there was any follow up here given previous discussions.

**Comment by maxpumperla** [comment]
@agibsonccc patiently wait 5 more minutes for my next PR

**Comment by saudet** [comment]
Not really, is this something that needs to get done right away? I mean if it's just copying pydl4j, might as well do it. For example, I'm not sure I'll be able to support already installed versions of Python, for example, just like Anaconda installs its own version of Python.

**Comment by agibsonccc** [comment]
So of note here is @sshepel starting to work on the CI here. Once we're up on maven central, this should be a lot easier. Figured I'd flag now to be sure.

**Comment by ShamsUlAzeem** [comment]
@maxpumperla this is related I believe: https://github.com/KonduitAI/konduit-serving/pull/61

**Comment by maxpumperla** [comment]
yeah, I know :) we have basic support for this already, so we could theoretically close the issue. but: once we have actual maven central releases I don't want people to build the project entirely from scratch (even if they don't know that's happening). leaving this open until then.

**Comment by maxpumperla** [comment]
closing now, since pydl4j interop seems to work with the latest PR #82
