### ISSUE TITLE
java.lang.NullPointerException: No output schemas specified in configuration!

### ISSUE THREAD

**Issue by philip-khor** [KonduitAI/konduit-serving#164]
Opening this for tracking: I think the cause has already been identified. 

Predicting from a Serving instance using the configuration https://github.com/KonduitAI/konduit-serving-examples/blob/master/yaml/deeplearning4j.yaml fails with `java.lang.NullPointerException: No output schemas specified in configuration!`. This also happens with other ModelStep configurations.

Building from sa/fixing-batchinputparser fixes the issue. Notably, in commit 14f54e06b00cfc6dc07b04d81d63123568bb0dc1, a schema is not initialized for ModelSteps.

```python
rand_image = np.random.randint(255, size=(1, 3, 224, 224)) / 255
konduit_yaml_path = "deeplearning4j.yaml"
server = server_from_file(konduit_yaml_path)
server.start()

client = client_from_file(konduit_yaml_path)
print(client.predict({"image_array": rand_image}))
server.stop()
```

Trace: https://gist.github.com/philip-khor/710f1f704428d492df51a62a30940bcd

**Comment by ShamsUlAzeem** [comment]
Fixed here: https://github.com/KonduitAI/konduit-serving/pull/195/files and here: https://github.com/KonduitAI/konduit-serving/pull/203/files/8532ceb852cd740a485923fda6259c263faf9c64#diff-f22a915af77dc6afcd0e566918691bc2R225
