### ISSUE TITLE
JSON schema mapping for non NDArray inputs might be wrong.

### ISSUE THREAD

**Issue by wmeddie** [KonduitAI/konduit-serving#17]
The server config code here: https://github.com/KonduitAI/konduit-serving/blob/km-demo/python/serve_pytorch.py does not work in the same way that is expected from the test code here: https://github.com/KonduitAI/konduit-serving/blob/4f5e01525160719e49057a4b4425a03b6688f325/python/tests/test_python_serving.py

The serve_pytorch.py code is specifying that it should accept a JSON similar to { "image": "path" } but the server returns the error `Specified root name image not found in input names.`  if you pose a JSON like that.  It turns out you have to post a JSON object with a key "default", but it does not automatically get mapped to the "image" key.

This might not necessarily be a bug.  It may be possible that it is working as intended but you must add a transform process in front.  It is something we should test.

**Comment by maxpumperla** [comment]
@wmeddie note that this error message is actually thrown on the client side:

https://github.com/KonduitAI/konduit-serving/blob/master/python/konduit/client.py#L152

the error indicates that the `data_input` dict provided to `predict` is not contained in the initially provided `input_names` of the `Client`. from the script you're using that does seem to be the case though. I'd be interested to see what exactly goes wrong there in Python (is the regex working as expected there?)

I'm in the middle of testing `client.py` at least a little bit now, so simple client-side errors like these will hopefully be caught soon.

**Comment by maxpumperla** [comment]
@kmotohas btw, could you share your model and inputs so we can make this scenario a test or example, once we find a solution?

**Comment by agibsonccc** [comment]
Any updates here?

**Comment by kmotohas** [comment]
Sorry I missed this.

I used this face detector model based on PyTorch. `detect_one.py` is a served code by the python runner.
https://github.com/kmotohas/Ultra-Light-Fast-Generic-Face-Detector-1MB (forked to my repo)
https://github.com/kmotohas/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/detect_one.py#L47
`serve_pytorch.py` is a code to serve the above code using the konduit python client.
https://github.com/KonduitAI/konduit-serving/blob/km-demo/python/serve_pytorch.py
Here everything is named `default` but an input variable name was set `image` before as Eduardo mentioned.

Below is a documentation of what I did for a demo last month.
https://gist.github.com/kmotohas/3c99909ea5c265a4beb87cf9b675f39b

**Comment by maxpumperla** [comment]
@kmotohas great, thanks for sharing this. I'll try to make this an example in `konduit-serving`. Do I understand correctly that your demo works? If so, what problem remains exactly?

Also, quick idea: if you set your work dir as `workdir = os.path.abspath('.')` the user doesn't have to adapt it manually.

**Comment by maxpumperla** [comment]
one last question, what exactly is the variable `default` supposed to be in that line:
https://github.com/kmotohas/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/detect_one.py#L47

I don't see it defined anywhere

**Comment by kmotohas** [comment]
@maxpumperla Thanks for your code review :)

I do not have any critical problems for now. But I could not find a way to differentiate names of input and output variables (here, input is bese64 encoded image and output is the number of faces in an image). Currently both are named as 'default'. This looks a bit confusing.

**Comment by maxpumperla** [comment]
@kmotohas I agree. I'll close this issue in favor of a new one re: variable naming conventions

**Comment by maxpumperla** [comment]
https://github.com/KonduitAI/konduit-serving/tree/master/python/examples/face_detection_pytorch

@kmotohas @ShamsUlAzeem extended example based on your demo

**Comment by kmotohas** [comment]
Cool!

**Comment by kmotohas** [comment]
I find the input json `{'image': <base64 encoded image>}` is exactly same as the returned output json `{'image': <base64 encoded image>`.
This is a case even if I change `output_names` e.g. "num_boxes".
https://github.com/KonduitAI/konduit-serving/commit/50396ace76f019c6bd5346cdbd744da6fd641018

**Comment by kmotohas** [comment]
sorry, this was wrong. just PYTHON_PATH was not properly set so the program aborted in the middle.
after this modification https://github.com/KonduitAI/konduit-serving/commit/264c70d99ca24fa4b1fe17080f4997b72aa600ea it runs correctly.

**Comment by maxpumperla** [comment]
@kmotohas this is nevertheless a bug, thanks for noticing. do you mind sending a quick PR for this?

**Comment by maxpumperla** [comment]
@kmotohas sorry, I see this behavior still, even with your changes. it does indeed return the original image...

**Comment by kmotohas** [comment]
I sent a PR https://github.com/KonduitAI/konduit-serving/pull/100
Can you try it in my `face_detection` branch?
It works in my environment of Ubuntu16.04 + CPU.

**Comment by maxpumperla** [comment]
@kmotohas I'll check it out, thanks for helping out here!
