### ISSUE TITLE
clarify and document input type for client

### ISSUE THREAD

**Issue by maxpumperla** [KonduitAI/konduit-serving#18]
https://github.com/KonduitAI/konduit-serving/blob/master/python/konduit/client.py#L95-L96

It's not quite clear what the input is _intended_ to be. the default value is a list, but providing a non-empty list will fail in this line

https://github.com/KonduitAI/konduit-serving/blob/master/python/konduit/client.py#L104

unless it's a list of pairs. It seems `dict` would be a better choice (well, `None` is even better, mutable default args are discouraged).

**Comment by agibsonccc** [comment]
@maxpumperla https://github.com/KonduitAI/konduit-serving/blob/ca762f71ed2be0be4caba19593a7f675adb47710/python/tests/test_client_serde.py#L27 I...think the default value should be a dict. Based on the test coverage, this list thing seems to be a mistake, especially since it's a helper method.
