### ISSUE TITLE
what is this regex intended to match?

### ISSUE THREAD

**Issue by maxpumperla** [KonduitAI/konduit-serving#19]
https://github.com/KonduitAI/konduit-serving/blob/485642123c362110cae5e76c42e08b869b329ea5/python/konduit/client.py#L150

it seems this would replace `\[1337\]default` by `default`. when is this relevant?

**Comment by maxpumperla** [comment]
I'm asking specifically about this, as https://github.com/KonduitAI/konduit-serving/issues/17 seems to have input name matching issues and I want to understand the intended behaviour.

**Comment by agibsonccc** [comment]
@maxpumperla this is intended to be matching partname[0 through 9]. Multi part batches get assembled allowing something like:
partname[0]
partname[1]

This allows you to send things like documents indicating which input should be which row or slice in the batch. A "name" is an "input name" in neural networks. An input name gets mapped to a part name.
