### ISSUE TITLE
Remove assert keyword from Java tests (replace with junit assert methods)

### ISSUE THREAD

**Issue by AlexDBlack** [KonduitAI/konduit-serving#209]
https://github.com/KonduitAI/konduit-serving/blob/master/konduit-serving-test/src/test/java/ai/konduit/serving/pipeline/steps/TransformProcessStepTest.java#L31

Using the Java assert keyword _might_ work for tests, but it's not safe as Java assertions aren't enabled by default. We should use junit assert methods instead

I haven't done a thorough review, there may be more instances of this.

**Comment by agibsonccc** [comment]
Ahh good find! I caught most of those. Thanks for finding this!

**Comment by AlexDBlack** [comment]
https://github.com/KonduitAI/konduit-serving/pull/237
