### ISSUE TITLE
hard-coded output names in pipeline executioner

### ISSUE THREAD

**Issue by maxpumperla** [KonduitAI/konduit-serving#22]
https://github.com/KonduitAI/konduit-serving/blob/4f5e01525160719e49057a4b4425a03b6688f325/konduit-serving-core/src/main/java/ai/konduit/serving/executioner/PipelineExecutioner.java#L375-L381

this seems off, unless I'm missing something.

**Comment by maxpumperla** [comment]
we always get `"default"` there, which sometimes might help, but can cause problems as well. we should have a test covering this.

**Comment by agibsonccc** [comment]
@maxpumperla just of note is the output adapters there are meant for 1 output only. I agree with you about test coverage there though.

**Comment by agibsonccc** [comment]
@maxpumperla ^ I think I fixed this. I looked at it again, not sure how I missed that.
