### ISSUE TITLE
CLI/Python API: Add the ability to list all running servers

### ISSUE THREAD

**Issue by AlexDBlack** [KonduitAI/konduit-serving#231]
Basically, the Konduit Serving equivalent of `docker ps`
https://docs.docker.com/engine/reference/commandline/ps/

In terms of implementation, this might be as simple as "list processes, see those that are Java, filter by launch args", in order to find any that are running locally.

Then, assuming we can find a way to get the port, we can add an endpoint to query information on each server, that can be reported back to the user.

**Comment by agibsonccc** [comment]
@AlexDBlack this would again rely on some sort of base line orchestration being implemented on the backend. You might want to look closer at the orchestration module.

**Comment by AlexDBlack** [comment]
Not necessarily. Proper orchestration would be a nicer solution, but there are solutions others (like writing a file to specified directory with the process ID + port etc) might work well enough until then.

**Comment by agibsonccc** [comment]
@AlexDBlack the orchestration module already has most of this implemented. You can list existing processes and everything. Each one registers as a node. Vertx implements most of this, and we bring it together in a cohesive main class. I would rather we just build on what's there first.
