### ISSUE TITLE
Config.yaml failed to load for models 

### ISSUE THREAD

**Issue by chiaweilim** [KonduitAI/konduit-serving#269]
Latest build of konduit-serving could not successfully serve DL4J, Keras model on konduit client.
[model failed log](https://gist.github.com/chiaweilim/df715978c28d1c71ee307b1f0f47a1ca)

Python scripts runs just fine.
[python script success log](https://gist.github.com/chiaweilim/0a56b307cc14dff43ebc71513cb449bd)

Yaml scripts are in [here](https://github.com/codenamewei/konduit-serving-use-cases)
Models can be downloaded from [here](https://drive.google.com/drive/folders/1v094WDWZrSlPeDHdqQqAoyudsz_tNRPS?usp=sharing)
The commit i'm using is master branch b014c6e

**Comment by ShamsUlAzeem** [comment]
@chiaweilim can you check the `model failed log` link. It's apparently navigating to a merge commit

**Comment by chiaweilim** [comment]
@ShamsUlAzeem my bad. [link ](https://gist.github.com/chiaweilim/df715978c28d1c71ee307b1f0f47a1ca)fixed

**Comment by AlexDBlack** [comment]
@chiaweilim I'm not seeing any sort of error in the log files you provide.

When you say "konduit-serving could not successfully serve DL4J, Keras model on konduit client" - what exactly do you mean? That inference requests are giving some sort of an error?

**Comment by chiaweilim** [comment]
right so for [model failed log](https://gist.github.com/chiaweilim/df715978c28d1c71ee307b1f0f47a1ca) it basically did not proceed after _**Blas vendor: [OPENBLAS]**_

and if i patiently wait long enough, it will end up with _**The server failed to start.**_

while python script able to serve successfully 
 [python script success log](https://gist.github.com/chiaweilim/0a56b307cc14dff43ebc71513cb449bd)

for now i have trouble finding the logs if the server did not start..
perhaps you or @ShamsUlAzeem can advice me more..

I've figure where to find logs after the server started from merging of #256 though

**Comment by AlexDBlack** [comment]
Ah, so you suspect it is running into some sort of deadlock - i.e., gets stuck, then times out.
We'll need to try and reproduce it to say much more...

Something that could help us debug though is a stack trace:
First, start the server.
Then run: `jps -l` to list running java processes. There might be a few, look for the one that is konduit serving related (probably mentions konduit serving or vertx?)
Get the process ID from that (number on the left)

Then run `jstack 12345 > myFile.txt` where 12345 should be replaced with the process number from the jps output.

**Comment by chiaweilim** [comment]
here's the log file from jstack @AlexDBlack 
[failed_log.txt](https://github.com/KonduitAI/konduit-serving/files/4370319/failed_log.txt)

**Comment by AlexDBlack** [comment]
Thanks. OK, so it's not a deadlock during model loading then... One of us will need to reproduce this locally, not sure what's up :/

**Comment by chiaweilim** [comment]
@alexanderst 
let me know if anything else i can help
as much for the models, config repo, i have make them available as below
Yaml scripts are in [here](https://github.com/codenamewei/konduit-serving-use-cases)
Models can be downloaded from [here](https://drive.google.com/drive/folders/1v094WDWZrSlPeDHdqQqAoyudsz_tNRPS?usp=sharing)

Im using master branch of Konduit-Serving for this.

**Comment by ShamsUlAzeem** [comment]
I'll take a look at this after I fix the CI related issues. Maybe this one will get sorted out with them.

**Comment by chiaweilim** [comment]
thanks @ShamsUlAzeem

**Comment by chiaweilim** [comment]
a quick test shows that the problem persists after fixing of CI issues still

**Comment by ShamsUlAzeem** [comment]
I'll take a look

**Comment by ShamsUlAzeem** [comment]
@chiaweilim @AlexDBlack  found the issue. Not sure why it's not logging the exception on console window. The issue was because of inference configuration not being able to instantiate from the generated config json. I'll send a PR for this soon. Hopefully, today.
