### ISSUE TITLE
./konduit-init --chip cpu show some error

### ISSUE THREAD

**Issue by wangfeng-skymind** [KonduitAI/konduit-serving#309]
[root@iZ2ze3hiduvxw3kac9o07jZ bin]# ./konduit-init --chip cpu
HEAD is now at 6019215... Fixing tests
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
Running command: /root/.konduit-serving/source/mvnw -Puberjar,tensorflow clean install -Dmaven.test.skip=true -Djavacpp.platform=linux-x86_64 -Dchip=cpu -Ppython -Ppmml -Dspin.version=all
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 11 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 11 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 3.10
[INFO] os.detected.version.major: 3
[INFO] os.detected.version.minor: 10
[INFO] os.detected.release: centos
[INFO] os.detected.release.version: 7
[INFO] os.detected.release.like.centos: true
[INFO] os.detected.release.like.rhel: true
[INFO] os.detected.release.like.fedora: true
[INFO] os.detected.classifier: linux-x86_64
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] konduit-serving                                                    [pom]
[INFO] konduit-serving-api                                                [jar]
[INFO] konduit-serving-core                                               [jar]
[INFO] konduit-serving-codegen                                            [jar]
[INFO] konduit-serving-orchestration                                      [jar]
[INFO] konduit-serving-pmml                                               [jar]
[INFO] konduit-serving-tfjava                                             [jar]
[INFO] konduit-serving-native                                             [jar]
[INFO] konduit-serving-python                                             [jar]
[INFO] konduit-serving-distro-bom                                         [jar]
[INFO] konduit-serving-uberjar                                            [jar]
[INFO] 
[INFO] -----------------< ai.konduit.serving:konduit-serving >-----------------
[INFO] Building konduit-serving 0.1.0-SNAPSHOT                           [1/11]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ konduit-serving ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven) @ konduit-serving ---
[INFO] 
[INFO] --- os-maven-plugin:1.6.1:detect (default) @ konduit-serving ---
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 3.10
[INFO] os.detected.version.major: 3
[INFO] os.detected.version.minor: 10
[INFO] os.detected.release: centos
[INFO] os.detected.release.version: 7
[INFO] os.detected.release.like.centos: true
[INFO] os.detected.release.like.rhel: true
[INFO] os.detected.release.like.fedora: true
[INFO] os.detected.classifier: linux-x86_64
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ konduit-serving ---
[INFO] Installing /root/.konduit-serving/source/pom.xml to /root/.m2/repository/ai/konduit/serving/konduit-serving/0.1.0-SNAPSHOT/konduit-serving-0.1.0-SNAPSHOT.pom
[INFO] 
[INFO] ---------------< ai.konduit.serving:konduit-serving-api >---------------
[INFO] Building konduit-serving-api 0.1.0-SNAPSHOT                       [2/11]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ konduit-serving-api ---
[INFO] Deleting /root/.konduit-serving/source/konduit-serving-api/target
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven) @ konduit-serving-api ---
[INFO] 
[INFO] --- os-maven-plugin:1.6.1:detect (default) @ konduit-serving-api ---
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 3.10
[INFO] os.detected.version.major: 3
[INFO] os.detected.version.minor: 10
[INFO] os.detected.release: centos
[INFO] os.detected.release.version: 7
[INFO] os.detected.release.like.centos: true
[INFO] os.detected.release.like.rhel: true
[INFO] os.detected.release.like.fedora: true
[INFO] os.detected.classifier: linux-x86_64
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ konduit-serving-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/.konduit-serving/source/konduit-serving-api/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ konduit-serving-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 79 source files to /root/.konduit-serving/source/konduit-serving-api/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/pipeline/BasePipelineStep.java:[34,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/util/SchemaTypeUtils.java:[39,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/util/MetricRenderUtils.java:[25,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/input/conversion/BatchInputParser.java:[37,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/input/conversion/BatchInputParser.java:[39,34] package org.nd4j.linalg.primitives does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/input/conversion/BatchInputParser.java:[229,13] cannot find symbol
  symbol:   class Pair
  location: class ai.konduit.serving.input.conversion.BatchInputParser
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/util/WritableValueRetriever.java:[26,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/output/adapter/ClassificationMultiOutputAdapter.java:[28,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/util/JsonSerdeUtils.java:[29,21] package org.nd4j.base does not exist
[INFO] 9 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for konduit-serving 0.1.0-SNAPSHOT:
[INFO] 
[INFO] konduit-serving .................................... SUCCESS [  0.277 s]
[INFO] konduit-serving-api ................................ FAILURE [  4.914 s]
[INFO] konduit-serving-core ............................... SKIPPED
[INFO] konduit-serving-codegen ............................ SKIPPED
[INFO] konduit-serving-orchestration ...................... SKIPPED
[INFO] konduit-serving-pmml ............................... SKIPPED
[INFO] konduit-serving-tfjava ............................. SKIPPED
[INFO] konduit-serving-native ............................. SKIPPED
[INFO] konduit-serving-python ............................. SKIPPED
[INFO] konduit-serving-distro-bom ......................... SKIPPED
[INFO] konduit-serving-uberjar ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.011 s
[INFO] Finished at: 2020-05-07T09:12:07+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project konduit-serving-api: Compilation failure: Compilation failure: 
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/pipeline/BasePipelineStep.java:[34,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/util/SchemaTypeUtils.java:[39,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/util/MetricRenderUtils.java:[25,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/input/conversion/BatchInputParser.java:[37,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/input/conversion/BatchInputParser.java:[39,34] package org.nd4j.linalg.primitives does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/input/conversion/BatchInputParser.java:[229,13] cannot find symbol
[ERROR]   symbol:   class Pair
[ERROR]   location: class ai.konduit.serving.input.conversion.BatchInputParser
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/util/WritableValueRetriever.java:[26,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/output/adapter/ClassificationMultiOutputAdapter.java:[28,21] package org.nd4j.base does not exist
[ERROR] /root/.konduit-serving/source/konduit-serving-api/src/main/java/ai/konduit/serving/util/JsonSerdeUtils.java:[29,21] package org.nd4j.base does not exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :konduit-serving-api
Traceback (most recent call last):
  File "/root/.konduit-serving/source/build_jar.py", line 116, in <module>
    os.path.join(args.source, args.target),
  File "/usr/local/python3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.konduit-serving/source/konduit-serving-uberjar/target/konduit-serving-uberjar-0.1.0-SNAPSHOT-all-linux-x86_64-cpu.jar'

**Comment by AlexDBlack** [comment]
All of these "org.nd4j.base does not exist", "org.nd4j.linalg.primitives" type messages are due to a recent change on DL4J/ND4J snapshots - there were breaking API changes that were updated in Konduit Serving here:
https://github.com/KonduitAI/konduit-serving/pull/300

Looks like konduit-init is using an old commit hash before that PR: https://github.com/KonduitAI/konduit-serving/releases

cc @ShamsUlAzeem - we'll need to make a new tag and update the python package.

**Comment by ShamsUlAzeem** [comment]
Thanks for the flag! For now using `konduit-init --chip cpu -d` would download the binaries and you'll be able to use it. I'll add a new tag and the python package should be able  to automatically pick up the latest tag.

**Comment by ShamsUlAzeem** [comment]
@wangfeng-skymind the new tag is up now. It should work with just running the same command `konduit-init --chip cpu`. If not, you can specify a release tag explicitly with `konduit-init --chip cpu --tag cli_base_4`. If both doesn't work then you can just download the pre-compiled libraries with `konduit-init --chip cpu -d`

**Comment by wangfeng-skymind** [comment]
great, now has been solved
