### ISSUE TITLE
Links are out of date in notebook

### ISSUE THREAD

**Issue by agibsonccc** [KonduitAI/konduit-serving#31]
Ensure we change konduit to konduit-serving -> 
https://github.com/KonduitAI/konduit-serving/blob/master/docker/notes/running-python-server.ipynb

**Comment by maxpumperla** [comment]
@agibsonccc yeah, remember when I asked you if naming the whole thing `konduit` would work as well? :D

**Comment by maxpumperla** [comment]
@ShamsUlAzeem I'm working on a little CLI tool right now that let's you automatically send HEAD requests to all links in a project and returns potential error codes. this way we don't have to click on links like chimps.
