### ISSUE TITLE
Annotation processors incompatible with IntelliJ incremental compilation?

### ISSUE THREAD

**Issue by AlexDBlack** [KonduitAI/konduit-serving#362]
Currently, sometimes, if you modify something annotated with `@CanRun` IntelliJ's build will fail with this:
```
Error:java: java.lang.IllegalStateException: No class in this module is annotated with @ModuleInfo - a class with @ModuleInfo("your-module-name" should be added to the module that has the @CanRun(...) annotation
```
This is an internal error coming from our annotation processor; the error there isn't correct (the required `@ModuleInfo` annotation definitely exists, and Maven builds fine.

Looks like incremental compilation is the cause of this problem - currently one of the annotation processors expects to receive annotations from 2 different classes; however, this is only guaranteed when the entire module is compiled (and not some classes compiled incrementally).

**Comment by ShamsUlAzeem** [comment]
Saw this as well. Should this be reported to jetbrains?

**Comment by AlexDBlack** [comment]
Maybe, maybe not. I'd need to more very carefully read the finer points of annotation processing in Java first, to see how it's supposed to interact with incremental compilation (it's possible this isn't supported/recommended generally).
A workaround for now is just to do "build -> rebuild project" in IntelliJ
