### ISSUE TITLE
How to pass variables from python step to the following non-python step in Konduit pipeline?

### ISSUE THREAD

**Issue by terU3760** [KonduitAI/konduit-serving#488]
Is it possible to pass variables from a python step to the following step that is not a python step? In the configuration yaml of pipeline of Konduit we configure some python step before a non-python step, e.g. after some processing the python step has produced an image as a variable, and then we wish to show this image so we want use the show image step. But the ShowImageStep is written in Java obviously not python, is it possible to do so?

**Comment by agibsonccc** [comment]
Answered here, https://community.konduit.ai/t/how-to-pass-variables-from-python-step-to-the-following-non-python-step-in-konduit-pipeline/1189/1 closing.

**Comment by terU3760** [comment]
@agibsonccc Could you please answer https://community.konduit.ai/t/how-to-pass-variables-from-python-step-to-the-following-non-python-step-in-konduit-pipeline/1189/1, too? It seems that eduardo hadn't fully answered my question. Could you please also help me on this question?

**Comment by ShamsUlAzeem** [comment]
@terU3760 is it answered now? Or do I need to reopen this?
