### ISSUE TITLE
Clean build without -P test profile

### ISSUE THREAD

**Issue by sshepel** [KonduitAI/konduit-serving#60]
Would be nice to have clean build without `-P test` profile that adds some test dependencies, and at the same time has dependencies required for build.

**Comment by ShamsUlAzeem** [comment]
@sshepel were you able run a build without the test profile?

**Comment by ShamsUlAzeem** [comment]
Something like this should work: `mvn -Puberjar clean install -Dmaven.test.skip=true -Djavacpp.platform=windows-x86_64  -Dchip=cpu -Ppython -Ppmml`

**Comment by sshepel** [comment]
@ShamsUlAzeem yeap, looks like now I'm able to build without `test` profile, thanks.
