### ISSUE TITLE
Document TransformProcessStep. 

### ISSUE THREAD

**Issue by ShamsUlAzeem** [KonduitAI/konduit-serving#74]
Create a basic example of how to create a transform process with the python SDK and serve it. For now, we'll document with the currently available API set using `pyjnius` and later on, we'll switch towards using pydatavec. 

### Creating an Example
- [x] Write an example of a simple transform process serving through konduit-serving
- [x] Push the source code to [konduit-serving-examples](https://github.com/KonduitAI/konduit-serving-examples) repo

### Documentation 
- [x] Document the created example

**Comment by philip-khor** [comment]
https://github.com/KonduitAI/konduit-serving-examples/pull/8

**Comment by philip-khor** [comment]
Done at https://serving.oss.konduit.ai/examples/datavec
