### ISSUE TITLE
Document a pytorch example using PythonPipelineStep

### ISSUE THREAD

**Issue by ShamsUlAzeem** [KonduitAI/konduit-serving#76]
Serve Motohashi San's pytorch [example]( https://github.com/KonduitAI/konduit-serving/blob/km-demo/python/serve_pytorch.py) using python pipeline step. 

### Creating an Example
- [x] Using the above-linked example, create a python pipeline step to serve the model. 
- [x] Push the source code to [konduit-serving-examples](https://github.com/KonduitAI/konduit-serving-examples) repo

### Documentation 
- [x] Document the created example

**Comment by philip-khor** [comment]
Worked on in KonduitAI/konduit-serving-examples#5

**Comment by philip-khor** [comment]
Done at https://serving.oss.konduit.ai/examples/onnx
