### ISSUE TITLE
Establish basic safeguards to ensure docs don't outdate too quickly

### ISSUE THREAD

**Issue by maxpumperla** [KonduitAI/konduit-serving#78]
Since we still work on API changes in Java, fix the Python SDK, and modify the CLI, our separate system of docs using gitbook turns bad quicker than sushi on a warm summer day.

At least for the Python part of the docs I created a `docs` folder to host basic markdown files that can be synced with gitbook. Also, I'd like to propose to use `doctest` to do smoke tests on examples listed there, so that at least the API is up to date. with proper git tag management we could even ensure intact examples for different API versions etc.

https://github.com/KonduitAI/konduit-serving/tree/master/python/docs

the docs folder also gives us a place to structure our thoughts and collect what users really need to get started. I fear that otherwise we end up with a random collection of unrelated articles skil-style.

**Comment by ShamsUlAzeem** [comment]
Maybe we can also utilize what Alex has created for dl4j for docs management. We can also make this part of our CI that triggers events like creating issues for outdated docs.

**Comment by agibsonccc** [comment]
This has been implemented. @maxpumperla mind linking the fix? I will close this.

**Comment by ShamsUlAzeem** [comment]
I think this was it: https://github.com/KonduitAI/konduit-serving/pull/83
