### ISSUE TITLE
NUMPY output not returned by Python Client if input is JSON

### ISSUE THREAD

**Issue by philip-khor** [KonduitAI/konduit-serving#86]
If JSON input type is specified and `return_output_type` and `endpoint_output_type` are specified as NUMPY, the following error results: 

> ERROR a.k.s.c.PipelineRouteDefiner - Request failed with cause
java.lang.IllegalArgumentException: No enum constant ai.konduit.serving.config.Output.PredictionType.NUMPY

even though PredictionType is not specified in the configuration. 

See https://gist.github.com/philip-khor/37f73a39e82a777752ad1756d84d0577 for reproducible example

**Comment by maxpumperla** [comment]
https://github.com/KonduitAI/konduit-serving/blob/4f5e01525160719e49057a4b4425a03b6688f325/konduit-serving-api/src/main/java/ai/konduit/serving/config/Output.java#L35-L42

`return_output_type` maps to PredictionType, which indeed does not have `NUMPY`. we'll need to see how to handle this then.

**Comment by agibsonccc** [comment]
This should generally be RAW which won't trigger an output adapter.

**Comment by ShamsUlAzeem** [comment]
I don't think this issue is relevant anymore since we've changed the APIs quite a bit. Look at the following PRs for reference: https://github.com/KonduitAI/konduit-serving/pull/101/files and https://github.com/KonduitAI/konduit-serving/pull/203
