### ISSUE TITLE
Redundant dimension is implicitly added to axis 0 of numpy array when it is sent to konduit server

### ISSUE THREAD

**Issue by kmotohas** [KonduitAI/konduit-serving#87]
The shape of numpy array is changed before/after being sent to the konduit server using the python client.

```
# client
img = cv2.cvtColor(cv2.imread('./test_b07a37e9.jpg', 1), cv2.COLOR_BGR2RGB)
print(img.shape)  # (2827, 1929, 3)
predicted = client.predict({'default': img.astype('int16')})  # since java does not have uint8 type
```

```
# server (python code itself is served in this case)
img = default
print(img.shape)  # (1, 2827, 1929, 3)
```

Is this intended feature?

**Comment by saudet** [comment]
That would be the batch size, so I'm think that's alright.

**Comment by kmotohas** [comment]
hmm, but if one sends, say, 5 images at the same time to server, then its shape would be changed to (1, 5, 2827, 1929, 3)... :(

**Comment by maxpumperla** [comment]
that seems to happen server-side. we need to further investigate this

**Comment by agibsonccc** [comment]
I'll look in to this.

**Comment by kmotohas** [comment]
@maxpumperla Below is simple code to reproduce the issue.
```python:
import numpy as np
print(image.shape)
num_boxes = np.array(51)
```
If you replace lines of `detect_image.py` with this, you would see the shape is `(1, 478, 720, 3)` though originally it is `(478, 720, 3)`.

**Comment by maxpumperla** [comment]
#142 fixes this, thanks for reporting @kmotohas
