### ISSUE TITLE
Distinguish between data structures and data formats

### ISSUE THREAD

**Issue by philip-khor** [KonduitAI/konduit-serving#88]
When users are writing configs, it can be quite tricky to distinguish data formats ("JSON",  "ÄRROW", "NUMPY") and types that represent data structures ("INT", "STR", "FLOAT", "BOOL", "NDARRAY", "LIST").

It may be good to refer to "JSON", "ÄRROW", "NUMPY", etc. as "formats" and "INT", "STR", "FLOAT", "BOOL", "NDARRAY", "LIST" as 'types' throughout.

**Comment by maxpumperla** [comment]
@philip-khor refer to them where exactly? in documentation, or do you propose another naming convention in the API? If so, can you try to make a concrete suggestion?

**Comment by philip-khor** [comment]
A naming convention in the API, if possible. I understand this might be a drastic change, so I'm totally fine if we give this issue a pass.

If I'm writing a configuration, it can be a little confusing when to use NUMPY or NDARRAY. The data structures are passed to an argument named `input_data_types`, e.g.
```python 
tensor_data_types_config = TensorDataTypesConfig(
        input_data_types={'input_layer': 'NDARRAY'}
        )
```
and the data *formats* (JSON, NUMPY, etc.) are passed to an argument named `input_data_type` in `ServingConfig`, e.g. 

```python 
serving_config = ServingConfig(
    http_port=port,
    input_data_type='NUMPY',
    output_data_type='NUMPY'
)
```

If it were named *input_data_format*, it might be clearer for the user: 

```python 
serving_config = ServingConfig(
    http_port=port,
    input_data_format='NUMPY',
    output_data_format='NUMPY'
)
```

**Comment by maxpumperla** [comment]
@philip-khor thanks, completely agree. does this only affect Serving Config or does this inconsistency pop up somewhere else?

**Comment by philip-khor** [comment]
This may also affect `Client()`. 
https://github.com/KonduitAI/konduit-serving/blob/d5866436d3bcd25ea043860b9654ce9cef17e98c/python/konduit/client.py#L12-L13
