### ISSUE TITLE
python "Server" ignores an environment variable of "KONDUIT_JAR_PATH"

### ISSUE THREAD

**Issue by kmotohas** [KonduitAI/konduit-serving#89]
https://github.com/KonduitAI/konduit-serving/blob/master/python/konduit/server.py#L25

```python:
class Server(object):
    def __init__(self, inference_config=None, serving_config=None, steps=None,
                 extra_start_args='-Xmx8g', config_path='config.json',
                 jar_path='konduit.jar'):
```

It tries to find `konduit.jar` in a current directory for now.
I think this `jar_path='konduit.jar'` should be something like `jar_path=os.environ['KONDUIT_JAR_PATH']`.

Any thought?

**Comment by maxpumperla** [comment]
@kmotohas yes, that's what it should be. thanks, spot on.
