### ISSUE TITLE
Document the basic implementation of Konduit CLI

### ISSUE THREAD

**Issue by ShamsUlAzeem** [KonduitAI/konduit-serving#99]
Max has created an initial implementation of [konduit CLI](https://github.com/KonduitAI/konduit-serving/pull/61) which can build jar files, serve python steps, models and a few other things. A few examples and a more detail documentation is needed for that:

### Creating Examples
- [x] Write examples of using different iterations of the konduit CLI. This can include building the jar file, serving a python step, serving a model etc among several other things.
- [x] Push the source code to [konduit-serving-examples](https://github.com/KonduitAI/konduit-serving-examples) repo

### Documentation 
- [x] Document the created examples

**Comment by philip-khor** [comment]
- [ ] Ensure YAML documentation is complete 
  - [ ] Write YAML documentation alongside current Python examples 
  - [ ] Write up basic Keras example
- [ ] Write up CLI documentation for serving and stopping 
- [ ] Write a CLI documentation page README-style for getting started with Konduit (?) (init, serve, predict-numpy, stop-server)

**Comment by ShamsUlAzeem** [comment]
@philip-khor great work. Did the keras model import work for you?

**Comment by philip-khor** [comment]
Yep it did, cheers :)

**Comment by philip-khor** [comment]
CLI examples at 
- https://serving.oss.konduit.ai/installation for init and build 
- https://serving.oss.konduit.ai/yaml-configurations for serve, predict-numpy, stop-server

Also added YAML instructions for: 
- Python pipeline steps https://serving.oss.konduit.ai/python
- All examples except DataVec, which is not currently supported https://serving.oss.konduit.ai/examples

Also added Keras example https://serving.oss.konduit.ai/examples/keras

PR at konduit-serving-examples to be cleaned up
